# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
version: 2.1

commands:
  restore-cache:
    description: Custom cache restore from S3
    parameters:
      cache-key:
        type: string
    steps:
      - run: 
          name: "Restore cache if a matching key is found in S3"
          command: |                 
                # Check if the folder name exists in S3
                if aws s3 ls "s3://vijay-custom-cache/<< parameters.cache-key >>" >/dev/null 2>&1; then
                    echo "Cache key found!...will restore cache now"
                    aws s3 sync "s3://vijay-custom-cache/<< parameters.cache-key >>" "./<< parameters.cache-key >>"
                    echo "Sync completed!"
                else
                    echo "Key not found in S3: << parameters.cache-key >>"
                fi

  save-cache:
    description: Custom cache store to S3
    parameters:
      cache-key:
        type: string
      cache-path:
        type: string
    steps:
      - run:
          name: "Save cache to s3 bucket"
          command: aws s3 cp << parameters.cache-path >> s3://vijay-custom-cache/<< parameters.cache-key >>/<< parameters.cache-path >>

jobs:
  s3-cache:
    parameters:
      cache-path:
        type: string
      cache-key:
        type: string
    docker:
      - image: cimg/base:stable
    steps:
      - save-cache:
             cache-path: << parameters.cache-path >>
             cache-key: << parameters.cache-key >>
