version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.1
  shellcheck: circleci/shellcheck@3.1
  cli: circleci/circleci-cli@0.1.9

filters: &filters
  tags:
    only: /.*/

jobs:
  create-orb:
    docker:
      - image: circleci/circleci-cli:latest
    steps:
      - cli/install
      - run: echo "the CLI is now installed"
      - cli/setup:
          token: CIRCLE_TOKEN
      - run: circleci info org
      - run: circleci orb create $CIRCLE_USERNAME/continuation --no-prompt


workflows:
  lint-pack:
    jobs:
      #- create-orb:
      #    context: org-global
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          shell: bash
          filters: *filters
      - orb-tools/publish:
          orb-name: vjpandian/s3-cache
          vcs-type: << pipeline.project.type >>
          requires:
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
            - shellcheck/check
      
          # Use a context to hold your publishing token.
          context: org-global
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: vjpandian/s3-cache
          requires: [orb-tools/lint, orb-tools/pack, orb-tools/review, shellcheck/check]
          filters: *filters